// MajorDoc — jeu de données de DÉMONSTRATION.
// Contenu volontairement fictif : aucun PMID, aucun DOI, aucune référence réelle.
// Sert uniquement à visualiser le rendu du board avant le premier vrai run.

import { rangRevue } from './rank.mjs';

const A = [
  {
    theme: 'Diabète',
    typeEtude: 'Essai randomisé',
    journal: 'The Lancet Diabetes & Endocrinology',
    journalAbrege: 'Lancet Diabetes Endocrinol',
    interet: 5,
    niveau_preuve: 'Élevé',
    accesLibre: false,
    titre: '[EXEMPLE] Once-weekly incretin co-agonist versus basal insulin in insulin-naive type 2 diabetes: a phase 3 randomised trial',
    titre_fr: "[Exemple] Co-agoniste incrétine hebdomadaire versus insuline basale chez le diabétique de type 2 naïf d'insuline",
    accroche: "Sur 52 semaines, le co-agoniste hebdomadaire réduit l'HbA1c de 0,6 point de plus que l'insuline glargine, avec 7 kg de perte de poids en plus.",
    contexte: "L'intensification après échec des antidiabétiques oraux repose encore largement sur l'insuline basale, au prix d'une prise de poids et d'un risque hypoglycémique. La place des co-agonistes incrétines à ce stade restait à préciser.",
    methode: "Essai de phase 3, randomisé, ouvert, 1 842 patients naïfs d'insuline, HbA1c 7,5–11 %, IMC ≥ 25. Randomisation 1:1 co-agoniste hebdomadaire versus glargine U100 titrée. Critère principal : variation d'HbA1c à 52 semaines (marge de non-infériorité 0,3 %, puis test de supériorité).",
    resultats: "HbA1c : −2,1 % vs −1,5 % (différence −0,62 ; IC95% −0,74 à −0,50 ; p < 0,001). Poids : −8,4 kg vs +1,9 kg. Cible < 7 % atteinte par 78 % vs 51 %. Hypoglycémies < 3,0 mmol/L : 0,9 vs 4,7 épisodes/patient-année. Effets digestifs 34 % vs 6 %, arrêts pour intolérance 6,1 %.",
    conclusion: "Le co-agoniste hebdomadaire est supérieur à l'insuline basale sur le contrôle glycémique et le poids, au prix d'une tolérance digestive moins bonne.",
    pour_la_pratique: "Argument de plus pour retarder l'insuline basale chez le DT2 en surpoids sans carence insulinique franche. Attention : aucune donnée cardiovasculaire dure ici, et le coût reste l'obstacle principal en ville. Ne modifie pas encore les recommandations SFD.",
    limites: "Essai ouvert (critère principal biologique, donc impact limité), durée de 52 semaines insuffisante pour les événements cardiovasculaires et rénaux. Financé par le laboratoire promoteur.",
    mots_cles: ['diabète de type 2', 'incrétines', 'insuline basale', 'perte de poids'],
    resumeSource: '[EXAMPLE ABSTRACT] BACKGROUND: Basal insulin remains the usual intensification step after oral agents fail. METHODS: In this open-label phase 3 trial, 1,842 insulin-naive adults with type 2 diabetes (HbA1c 7.5-11%, BMI at least 25) were randomly assigned 1:1 to a once-weekly incretin co-agonist or titrated glargine U100. The primary endpoint was change in HbA1c at 52 weeks. RESULTS: HbA1c fell by 2.1% with the co-agonist and 1.5% with glargine (difference -0.62; 95% CI -0.74 to -0.50; p<0.001). Body weight changed by -8.4 kg versus +1.9 kg. A target below 7% was reached by 78% versus 51% of participants. Hypoglycaemia below 3.0 mmol/L occurred at 0.9 versus 4.7 events per patient-year. Gastrointestinal events affected 34% versus 6%; 6.1% discontinued for intolerance. CONCLUSIONS: The weekly co-agonist was superior for glycaemic control and weight, with poorer gastrointestinal tolerance.',
  },
  {
    theme: 'Thyroïde',
    typeEtude: 'Recommandation',
    journal: "Annales d'Endocrinologie",
    journalAbrege: "Ann Endocrinol (Paris)",
    interet: 5,
    niveau_preuve: 'Modéré',
    accesLibre: true,
    titre: "[EXEMPLE] Consensus SFE : prise en charge des nodules thyroïdiens de cytologie indéterminée (Bethesda III-IV)",
    titre_fr: '[Exemple] Consensus SFE — nodules thyroïdiens de cytologie indéterminée (Bethesda III-IV)',
    accroche: "Le consensus recommande une surveillance échographique à 12 mois plutôt qu'une lobectomie d'emblée pour les Bethesda III sans critère de risque échographique.",
    contexte: "Les cytologies indéterminées représentent 15 à 25 % des ponctions et exposent à un excès de chirurgies diagnostiques, dont 70 à 80 % s'avèrent bénignes.",
    methode: "Groupe de travail multidisciplinaire SFE, méthode Delphi à 3 tours, 28 experts, 41 propositions, accord retenu au-delà de 80 % de votes concordants. Revue systématique de la littérature 2015-2025 en support.",
    resultats: "Surveillance à 12 mois proposée en première intention pour Bethesda III sans critère EU-TIRADS 5 (accord 92 %). Répétition de la cytoponction non systématique (accord 85 %). Tests moléculaires réservés aux centres experts, en l'absence de remboursement en France (accord 88 %). Lobectomie recommandée pour Bethesda IV > 2 cm (accord 81 %).",
    conclusion: "Le consensus déplace le curseur vers une désescalade chirurgicale encadrée par l'échographie de risque.",
    pour_la_pratique: "Concrètement : moins de lobectomies diagnostiques pour les Bethesda III de petite taille et EU-TIRADS 3-4. Pensez à documenter le score EU-TIRADS dans le compte rendu, il devient l'élément qui conditionne la conduite à tenir.",
    limites: "Consensus d'experts et non essai comparatif ; le niveau de preuve sous-jacent reste faible pour plusieurs propositions. Applicabilité conditionnée à une échographie de qualité.",
    mots_cles: ['nodule thyroïdien', 'Bethesda', 'EU-TIRADS', 'consensus SFE'],
    resumeSource: "[EXAMPLE ABSTRACT] Indeterminate cytology accounts for 15 to 25% of thyroid nodule aspirations and exposes patients to diagnostic surgery that proves benign in 70 to 80% of cases. A multidisciplinary SFE working group of 28 experts ran a 3-round Delphi process on 41 propositions, retaining agreement above 80% of concordant votes, supported by a systematic review of the 2015-2025 literature. Ultrasound surveillance at 12 months is proposed first line for Bethesda III without an EU-TIRADS 5 feature (92% agreement). Repeat aspiration is not systematic (85%). Molecular testing is reserved for expert centres given the absence of reimbursement in France (88%). Lobectomy is recommended for Bethesda IV above 2 cm (81%).",
  },
  {
    theme: 'Obésité & nutrition',
    typeEtude: 'Méta-analyse',
    journal: 'BMJ',
    journalAbrege: 'BMJ',
    interet: 4,
    niveau_preuve: 'Modéré',
    accesLibre: true,
    titre: '[EXEMPLE] Weight regain after discontinuation of GLP-1 receptor agonists: systematic review and meta-analysis of 34 cohorts',
    titre_fr: "[Exemple] Reprise pondérale à l'arrêt des agonistes du GLP-1 : revue systématique et méta-analyse de 34 cohortes",
    accroche: "À 12 mois d'arrêt, les patients reprennent en moyenne 62 % du poids perdu (IC95% 55-69), avec une reprise plus rapide dans les 4 premiers mois.",
    contexte: "La question de la durée du traitement est devenue centrale, alors que les ruptures de traitement (coût, tolérance, pénurie) sont fréquentes.",
    methode: "Revue systématique PROSPERO, 34 cohortes, 12 480 patients ayant interrompu un agoniste GLP-1 après au moins 6 mois. Modèle à effets aléatoires. Critère principal : pourcentage du poids perdu repris à 12 mois.",
    resultats: "Reprise moyenne de 62 % du poids perdu (IC95% 55-69 ; I² = 71 %). Reprise de 41 % dès le 4e mois. HbA1c revenue au niveau pré-traitement chez 68 % des diabétiques. Le maintien d'un accompagnement diététique structuré atténue la reprise (différence 18 points, IC95% 9-27).",
    conclusion: "L'arrêt sans relais s'accompagne d'une reprise pondérale majoritaire dès la première année.",
    pour_la_pratique: "À dire au patient avant l'instauration, pas après : le traitement s'inscrit dans une logique chronique. Prévoir un plan de décroissance et un accompagnement diététique si un arrêt est envisagé.",
    limites: "Hétérogénéité forte (I² = 71 %), cohortes majoritairement observationnelles avec perdus de vue importants, pas de données au-delà de 24 mois.",
    resumeSource: '[EXAMPLE ABSTRACT] OBJECTIVE: To quantify weight regain after discontinuation of GLP-1 receptor agonists. DESIGN: Systematic review and meta-analysis (PROSPERO registered) of 34 cohorts including 12,480 patients who stopped a GLP-1 receptor agonist after at least 6 months of treatment, using random-effects models. The primary outcome was the percentage of lost weight regained at 12 months. RESULTS: Participants regained a mean 62% of lost weight at 12 months (95% CI 55 to 69; I2 = 71%), with 41% regained by month 4. HbA1c returned to pre-treatment values in 68% of participants with diabetes. Structured dietary follow-up attenuated regain by 18 percentage points (95% CI 9 to 27). CONCLUSION: Discontinuation without a relay strategy is followed by majority weight regain within the first year.',
    mots_cles: ['obésité', 'GLP-1', 'reprise pondérale', 'sevrage'],
    verif: { controles: 11, absents: ['18', '9'] },
  },
  {
    theme: 'Surrénale',
    typeEtude: 'Étude observationnelle',
    journal: 'European Journal of Endocrinology',
    journalAbrege: 'Eur J Endocrinol',
    interet: 3,
    niveau_preuve: 'Faible',
    accesLibre: false,
    titre: '[EXEMPLE] Cardiometabolic outcomes of mild autonomous cortisol secretion in adrenal incidentaloma: a 10-year cohort',
    titre_fr: "[Exemple] Devenir cardiométabolique de la sécrétion autonome modérée de cortisol dans l'incidentalome surrénalien : cohorte à 10 ans",
    accroche: "Une sécrétion autonome modérée double le risque d'événement cardiovasculaire à 10 ans (HR 2,04 ; IC95% 1,41-2,95) indépendamment de l'HTA.",
    contexte: "La sécrétion autonome modérée concerne jusqu'à 30 % des incidentalomes, sans consensus sur l'indication opératoire en l'absence de signes cliniques de Cushing.",
    methode: "Cohorte prospective multicentrique, 1 122 patients avec incidentalome, freinage minute > 50 nmol/L, suivi médian 9,8 ans. Modèle de Cox ajusté sur âge, sexe, IMC, HTA, diabète, tabac.",
    resultats: "Événement cardiovasculaire majeur : 18,3 % vs 9,7 % (HR ajusté 2,04 ; IC95% 1,41-2,95). Incidence du diabète 2,3 fois supérieure. Fractures vertébrales 14,1 % vs 6,2 %. La surrénalectomie (n = 143) était associée à une régression de l'HTA chez 42 % des opérés.",
    conclusion: "La sécrétion autonome modérée n'est pas un état bénin sur le plan cardiométabolique.",
    pour_la_pratique: "Renforce l'idée de dépister systématiquement l'ostéoporose et le diabète devant un incidentalome freinant mal. La chirurgie reste à discuter au cas par cas — les données restent observationnelles.",
    limites: "Absence de randomisation pour la surrénalectomie (biais d'indication majeur), définition du freinage variable entre centres, pas de dosage centralisé.",
    mots_cles: ['incidentalome', 'cortisol', 'surrénalectomie', 'risque cardiovasculaire'],
  },
  {
    theme: 'Os & calcium',
    typeEtude: 'Essai randomisé',
    journal: 'Journal of Clinical Endocrinology & Metabolism',
    journalAbrege: 'J Clin Endocrinol Metab',
    interet: 4,
    niveau_preuve: 'Élevé',
    accesLibre: false,
    titre: '[EXEMPLE] Sequential anabolic-then-antiresorptive versus antiresorptive-first therapy in severe postmenopausal osteoporosis',
    titre_fr: "[Exemple] Séquence anabolique puis antirésorptive versus antirésorptive d'emblée dans l'ostéoporose post-ménopausique sévère",
    accroche: "Commencer par l'anabolique gagne 4,1 points de densité minérale osseuse rachidienne à 24 mois par rapport à la séquence inverse.",
    contexte: "L'ordre des traitements conditionne le gain densitométrique, mais la pratique reste souvent dictée par les contraintes de remboursement.",
    methode: "Essai randomisé en ouvert, 604 femmes ménopausées avec T-score ≤ −3,0 ou fracture vertébrale prévalente. Bras A : anabolique 12 mois puis denosumab 12 mois. Bras B : denosumab 24 mois. Critère principal : variation de DMO rachidienne à 24 mois.",
    resultats: "DMO rachis : +14,8 % vs +10,7 % (différence 4,1 points ; IC95% 3,0-5,2 ; p < 0,001). Col fémoral : +6,2 % vs +4,4 %. Nouvelles fractures vertébrales : 3,1 % vs 5,4 % (essai non dimensionné sur ce critère).",
    conclusion: "La séquence anabolique-puis-antirésorptive est densitométriquement supérieure dans les formes sévères.",
    pour_la_pratique: "Confirme l'intérêt d'ouvrir par l'anabolique chez les patientes à très haut risque, et rappelle la règle : jamais d'anabolique après denosumab sans relais, sous peine de perte osseuse.",
    limites: "Critère principal densitométrique et non fracturaire ; essai en ouvert ; effectif insuffisant pour conclure sur les fractures.",
    mots_cles: ['ostéoporose', 'séquence thérapeutique', 'denosumab', 'DMO'],
  },
  {
    theme: 'Hypophyse',
    typeEtude: 'Revue systématique',
    journal: 'Nature Reviews Endocrinology',
    journalAbrege: 'Nat Rev Endocrinol',
    interet: 3,
    niveau_preuve: 'Modéré',
    accesLibre: false,
    titre: '[EXEMPLE] Long-term remission and cardiovascular risk in acromegaly: a systematic review of 47 cohorts',
    titre_fr: "[Exemple] Rémission au long cours et risque cardiovasculaire dans l'acromégalie : revue systématique de 47 cohortes",
    accroche: "La normalisation de l'IGF-1 ramène la surmortalité à celle de la population générale, mais seulement après cinq ans de contrôle soutenu.",
    contexte: "L'objectif biologique de la prise en charge est bien défini, l'effet réel sur la mortalité au long cours l'est moins.",
    methode: "Revue systématique de 47 cohortes (n = 21 340), méta-analyse des ratios de mortalité standardisés selon le statut biologique.",
    resultats: "SMR global 1,32 (IC95% 1,18-1,48). Chez les patients à IGF-1 normalisée depuis plus de 5 ans : SMR 1,06 (IC95% 0,91-1,24), soit un retour à la normale. Persistance d'une prévalence élevée d'apnées du sommeil (52 %) et d'arthropathie (61 %) malgré le contrôle biologique.",
    conclusion: "Le contrôle biologique durable normalise la mortalité mais pas la morbidité fonctionnelle.",
    pour_la_pratique: "Message à porter en consultation : le contrôle de l'IGF-1 est un objectif qui paie, mais il ne dispense pas du suivi de l'apnée du sommeil et de l'arthropathie, qui restent la principale plainte des patients contrôlés.",
    limites: "Hétérogénéité des définitions de rémission entre cohortes, données rétrospectives, biais de publication possible.",
    mots_cles: ['acromégalie', 'IGF-1', 'mortalité', 'apnée du sommeil'],
  },
  {
    theme: 'Gonades & fertilité',
    typeEtude: 'Étude observationnelle',
    journal: 'Diabetes Care',
    journalAbrege: 'Diabetes Care',
    interet: 3,
    niveau_preuve: 'Faible',
    accesLibre: true,
    titre: '[EXEMPLE] Metabolic phenotypes of polycystic ovary syndrome and long-term diabetes risk: a population-based study',
    titre_fr: '[Exemple] Phénotypes métaboliques du SOPK et risque de diabète au long cours : étude en population',
    accroche: "Le phénotype hyperandrogénique avec anovulation porte l'essentiel du surrisque de diabète (HR 3,1), les autres phénotypes se rapprochant de la population générale.",
    contexte: "Le SOPK est traité comme une entité unique en matière de dépistage métabolique, alors que ses phénotypes de Rotterdam diffèrent nettement.",
    methode: "Étude de cohorte en population, 18 220 femmes avec SOPK appariées à 72 880 témoins, suivi médian 12,4 ans, stratification par phénotype de Rotterdam.",
    resultats: "Diabète incident : HR global 2,2 (IC95% 1,9-2,5). Phénotype A (hyperandrogénie + anovulation + morphologie) : HR 3,1 (IC95% 2,6-3,7). Phénotype D (sans hyperandrogénie) : HR 1,2 (IC95% 0,9-1,6), non significatif. L'IMC expliquait environ 55 % de l'association.",
    conclusion: "Le surrisque métabolique du SOPK est largement porté par le phénotype hyperandrogénique.",
    pour_la_pratique: "Piste pour cibler le dépistage : HGPO régulière pour les phénotypes A et B, allègement possible pour le phénotype D normo-pondéral. À confirmer avant de modifier les protocoles.",
    limites: "Phénotypage rétrospectif sur données de registres, risque de classement erroné, absence de données sur l'hygiène de vie.",
    mots_cles: ['SOPK', 'phénotypes de Rotterdam', 'diabète', 'dépistage'],
  },
  {
    theme: 'Onco-endocrinologie',
    typeEtude: 'Essai clinique',
    journal: 'Thyroid',
    journalAbrege: 'Thyroid',
    interet: 2,
    niveau_preuve: 'Faible',
    accesLibre: false,
    titre: '[EXEMPLE] Active surveillance versus immediate surgery for low-risk papillary microcarcinoma: 7-year outcomes',
    titre_fr: '[Exemple] Surveillance active versus chirurgie immédiate dans le microcarcinome papillaire à faible risque : résultats à 7 ans',
    accroche: "À 7 ans, aucun décès spécifique dans les deux bras ; 11 % des patients surveillés ont finalement été opérés, sans perte de chance apparente.",
    contexte: "La surveillance active est proposée depuis une décennie au Japon, avec une diffusion encore limitée en Europe.",
    methode: "Étude prospective non randomisée, 892 patients avec microcarcinome papillaire < 10 mm sans extension, choix du patient entre surveillance et chirurgie, suivi médian 7,2 ans.",
    resultats: "Progression en taille ≥ 3 mm : 6,4 % du bras surveillance. Apparition d'une adénopathie : 2,1 %. Conversion chirurgicale : 11,3 %. Aucun décès spécifique. Hypoparathyroïdie définitive : 0 % vs 1,8 % ; dysphonie persistante : 0 % vs 2,4 %.",
    conclusion: "La surveillance active apparaît sûre à 7 ans dans une population sélectionnée.",
    pour_la_pratique: "Peu applicable en routine française en dehors de centres organisés : suppose une échographie de haute qualité, un circuit de suivi fiable et un patient adhérent. Utile comme argument dans la discussion partagée.",
    limites: "Absence de randomisation (le patient choisit son bras, donc biais de sélection majeur), population sélectionnée, recul insuffisant pour un cancer à évolution très lente.",
    mots_cles: ['microcarcinome papillaire', 'surveillance active', 'thyroïdectomie', 'désescalade'],
  },
];

const RECOS = [
  {
    organisme: 'HAS',
    sourceLabel: 'HAS — recommandations et guides',
    type: 'Recommandation',
    theme: 'Diabète',
    interet: 5,
    certitude: 'Résumé seul',
    titreOriginal: "[EXEMPLE] Prise en charge du diabète de type 2 de l'adulte — actualisation de la recommandation de bonne pratique",
    titre_court: "[Exemple] Diabète de type 2 : la HAS actualise sa stratégie médicamenteuse",
    accroche:
      "La HAS place les analogues du GLP-1 en deuxième intention chez le patient à haut risque cardiovasculaire, avant l'intensification par insuline.",
    ce_qui_change:
      "L'escalade thérapeutique n'est plus uniquement guidée par l'HbA1c : le risque cardiovasculaire et rénal devient un critère de choix explicite dès la deuxième ligne.",
    points_cles: [
      'Metformine maintenue en première intention chez tous les patients sans contre-indication.',
      "En deuxième intention, le choix se fait selon le profil : GLP-1 si haut risque cardiovasculaire ou obésité, SGLT2 si insuffisance cardiaque ou maladie rénale chronique.",
      "L'objectif d'HbA1c reste individualisé, avec une cible assouplie au-delà de 75 ans ou en cas de comorbidités.",
      "L'insulinothérapie est repositionnée après échec de deux lignes non insuliniques.",
    ],
    population: "Adulte diabétique de type 2, hors grossesse et hors diabète secondaire.",
    pour_la_pratique:
      "À intégrer aux ordonnances de renouvellement : chez un DT2 coronarien ou insuffisant rénal, la question n'est plus « faut-il intensifier » mais « avec quelle classe ». Vérifier les conditions de remboursement, qui n'ont pas suivi partout.",
  },
  {
    organisme: 'SFE',
    sourceLabel: "Société Française d'Endocrinologie",
    type: 'Consensus',
    theme: 'Thyroïde',
    interet: 4,
    certitude: 'Texte complet lu',
    titreOriginal: "[EXEMPLE] Consensus SFE-SFMN sur la prise en charge des nodules thyroïdiens de cytologie indéterminée",
    titre_court: '[Exemple] Nodules thyroïdiens indéterminés : la SFE cadre la désescalade',
    accroche:
      "Surveillance échographique à 12 mois plutôt que lobectomie d'emblée pour les Bethesda III sans critère de risque échographique.",
    ce_qui_change:
      "La chirurgie diagnostique cesse d'être la réponse par défaut. Le score EU-TIRADS devient l'élément qui conditionne la conduite à tenir, et doit donc figurer dans le compte rendu d'échographie.",
    points_cles: [
      'Surveillance à 12 mois en première intention pour les Bethesda III EU-TIRADS 3-4.',
      'Répétition de la cytoponction non systématique.',
      "Tests moléculaires réservés aux centres experts, faute de remboursement en France.",
      'Lobectomie recommandée pour les Bethesda IV de plus de 2 cm.',
    ],
    population: "Adulte porteur d'un nodule thyroïdien de cytologie Bethesda III ou IV, hors antécédent d'irradiation cervicale.",
    pour_la_pratique:
      "Demander systématiquement le score EU-TIRADS au radiologue. Le consensus donne un appui écrit pour ne pas adresser en chirurgie un Bethesda III de petite taille — utile face à un patient inquiet.",
  },
];

export function DIGEST_DEMO(config) {
  const aujourdhui = new Date().toISOString().slice(0, 10);
  return {
    date: aujourdhui,
    genereLe: new Date().toISOString(),
    alerteHeures: config?.fraicheur_alerte_heures ?? 48,
    specialite: config?.specialite ?? 'Endocrinologie – Diabétologie – Nutrition',
    themes: Object.keys(config?.themes ?? {}),
    demo: true,
    modele: null,
    scannes: 247,
    cout: '18 420 tokens entrée · 9 630 sortie · ≈ 0,17 €',
    edito: {
      titre: "La HAS rebat les cartes du diabète de type 2",
      points: [
        "La HAS actualise la stratégie médicamenteuse du diabète de type 2 : le risque cardiovasculaire guide désormais la deuxième ligne.",
        "Un co-agoniste incrétine hebdomadaire fait mieux que l'insuline basale en première intensification, HbA1c et poids (Lancet Diabetes Endocrinol).",
        "Le consensus SFE acte la désescalade chirurgicale devant les nodules Bethesda III sans critère de risque échographique (Annales d'Endocrinologie).",
        "À l'arrêt des GLP-1, deux tiers du poids perdu sont repris en un an : à annoncer avant l'instauration, pas après (BMJ).",
        "Dans l'ostéoporose sévère, ouvrir par l'anabolique reste densitométriquement supérieur (JCEM).",
      ],
      a_lire_en_priorite:
        "L'actualisation HAS sur le diabète de type 2 — elle est opposable et concerne la moitié de vos consultations.",
    },
    sourcesFr: [
      { source: 'has-recos', label: 'HAS — recommandations et guides', recus: 1, total: 40, fenetre: 180 },
      { source: 'sfe', label: "Société Française d'Endocrinologie", recus: 1, total: 12, fenetre: 180 },
      { source: 'sfd', label: 'Société Francophone du Diabète', recus: 0, total: 8, fenetre: 180 },
      { source: 'recomedicales', label: 'RecoMédicales — synthèses de recommandations', recus: 0, total: 25, fenetre: 120 },
    ],
    recos: RECOS.map((r, i) => ({
      id: `demo-reco:${i}`,
      lien: null,
      date: new Date(Date.now() - (i * 6 + 3) * 86400000).toISOString().slice(0, 10),
      ...r,
    })),
    sources: [
      { source: 'pubmed-hautevaleur', label: 'PubMed — essais & méta-analyses', recus: 38, total: 38, fenetre: 4 },
      { source: 'pubmed-revues-majeures', label: 'PubMed — revues majeures', recus: 24, total: 24, fenetre: 4 },
      { source: 'pubmed-large', label: 'PubMed — veille large', recus: 100, total: 412, fenetre: 4 },
      { source: 'annales-endocrinologie', label: "Annales d'Endocrinologie (SFE)", recus: 9, total: 9, fenetre: 60 },
    ],
    articles: A.map((a, i) => ({
      id: `demo:${i}`,
      pmid: null,
      doi: null,
      auteurs: 'Exemple A, Exemple B, Exemple C, et al.',
      date: new Date(Date.now() - (i % 4) * 86400000).toISOString().slice(0, 10),
      liens: { pubmed: null, doi: null, europepmc: null },
      score: 12 - i,
      ...a,
      // Le badge de revue est calculé comme en production : depuis le config.
      rangRevue: rangRevue(a, config ?? {}),
      resumeSource: undefined,
    })),
    // Trois articles sur dix portent un résumé d'origine : de quoi voir le
    // dépliant, et de quoi voir qu'il disparaît proprement quand il manque.
    textesSource: Object.fromEntries(
      A.map((a, i) => [`demo:${i}`, a.resumeSource]).filter(([, t]) => t)
    ),
  };
}
